// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
)

type Branch struct {
	BranchID     int32
	BranchName   sql.NullString
	MgrID        sql.NullInt32
	MgrStartDate sql.NullTime
}

type BranchSupplier struct {
	BranchID     int32
	SupplierName string
	SupplyType   sql.NullString
}

type Client struct {
	ClientID   int32
	ClientName sql.NullString
	BranchID   sql.NullInt32
}

type Employee struct {
	EmpID     int32
	FirstName sql.NullString
	LastName  sql.NullString
	BirthDay  sql.NullTime
	Sex       sql.NullString
	Salary    sql.NullInt32
	SuperID   sql.NullInt32
	BranchID  sql.NullInt32
}

type WorksWith struct {
	EmpID      int32
	ClientID   int32
	TotalSales sql.NullInt32
}
